version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: swift
    directory: /PingWarden
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
